---
# see https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Static check and build project
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check format of go sources
        run: |
          go fmt ./...
          git diff --exit-code

      - name: Check format of shell scripts
        run: |
          GO111MODULE=off go get -u mvdan.cc/sh/v3/cmd/shfmt
          find . -name \*.sh | xargs shfmt -d

      - name: Lint go sources
        run: |
          GO111MODULE=off go get -u golang.org/x/lint/golint
          golint -set_exit_status ./...


      - name: Install dependencies
        run: |
          sudo add-apt-repository ppa:ubuntu-lxc/daily -y
          sudo apt-get install -qq lxc-dev musl musl-tools libc6-dev pkg-config make

      - name: Build
        run: make

      - name: Run tests
        run: make test
