---
name: Build project with default make target
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo add-apt-repository ppa:ubuntu-lxc/daily -y
          sudo apt-get install -qq lxc-dev musl musl-tools libc6-dev pkg-config make

      - name: Build
        run: make

      - name: Run tests
        run: make test
